- hosts: demo
  tasks:
    - name: create directory
      ansible.builtin.file:
        path: $HOME/aaa
        state: directory
        mode: 0755
    - name: confirm
      ansible.builtin.shell:
        cmd: ls -d */
      register: ret
    - name: output
      ansible.builtin.debug:
        msg: "{{ ret.stdout_lines }}"