image:
  file: .gitpod.Dockerfile
tasks:
  - name: Build demo docker image
    init: docker-compose build
    command: docker image list
  - name: Run ansible & demo container
    init: docker-compose up -d
    command: docker container list
vscode:
  extensions:
    - golang.go
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-toolsai.jupyter
