image:
  file: .gitpod.Dockerfile
tasks:
  - name: Build & Run ansible & demo container
    init: docker-compose up -d --build
    command: docker container list
vscode:
  extensions:
    - golang.go
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-toolsai.jupyter
